gen-web-server/forums/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from forums.views import CategoryListView, ForumDetailView, TopicDetailView, TopicCreateView, PostCreateView


urlpatterns = patterns('',
    url(r'^$', CategoryListView.as_view(), name='overview'),
    url(r'^(?P<pk>\d+)/$', ForumDetailView.as_view(), name='forum'),
    url(r'^(?P<forum_id>\d+)/create/$', login_required(TopicCreateView.as_view()), name='topic_create'),
    url(r'^topic/(?P<pk>\d+)/$', TopicDetailView.as_view(), name='topic'),
    url(r'^topic/(?P<pk>\d+)/create/$', login_required(PostCreateView.as_view()), name='post_create'),
)

gen-web-server/gen-web-server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import index, connect, contact, profile


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('nano.blog.urls', namespace='blog')),
    url(r'^user/', include('nano.user.urls', namespace='user')),
    url(r'^user/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^connect/$', connect, name='connect'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^profile/$', profile, name='profile'),
]

gen-web-server/nano/blog/urls.py
from django.conf.urls import *

from nano.blog import views

urlpatterns = patterns('',
    url(r'^(?P<year>\d{4})/(?P<month>[01]\d)/(?P<day>[0123]\d)/$', views.list_entries_by_date),
    url(r'^(?P<year>\d{4})/(?P<month>[01]\d)/$', views.list_entries_by_year_and_month),
    url(r'^(?P<year>\d{4})/$',     views.list_entries_by_year),
    url(r'^latest/$',              views.list_latest_entries),
    url(r'^today/$',               views.list_entries_for_today),
    url(r'^$',                     views.list_entries, name='overview'),
)

gen-web-server/nano/user/urls.py
from django.conf.urls import *
from django.shortcuts import render

from nano.user import views

signup_done_data = {'template_name': 'nano/user/signup_done.html'}

# 'project_name' should be a setting
password_reset_data = {'project_name': 'CALS'}

urlpatterns = patterns('',
    url(r'^signup/$',           views.signup, name='signup'),
    url(r'^password/reset/$',   views.password_reset, password_reset_data, name='nano_user_password_reset'),
    url(r'^password/change/$',  views.password_change, name='nano_user_password_change'),
    url(r'^signup/done/$',      render, signup_done_data, name='nano_user_signup_done'),
)

gen-web-server/schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

from django.conf import settings
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import (
        CalendarByPeriodsView, CalendarView, EventView,
        OccurrenceView, EditOccurrenceView, DeleteEventView,
        EditEventView, CreateEventView, OccurrencePreview,
        CreateOccurrenceView, CancelOccurrenceView, FullCalendarView)

'''
'''
urlpatterns = patterns(
    '',
    # urls for Calendars
    url(r'^calendar/$',
    ListView.as_view(queryset=Calendar.objects.all(),
                        template_name='schedule/calendar_list.html'),
    name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name="calendar_home",
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(), 
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name="edit_occurrence"),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date"),

    # feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    
    # api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),
    url(r'^api/move_or_resize/$', 
        'schedule.views.api_move_or_resize_by_code',
        name='api_move_or_resize'),
    url(r'^api/select_create/$', 
        'schedule.views.api_select_create',
        name='api_select_create'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    )

gen-web-server/templates/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'forums/style.css'%}" />
<script type="text/javascript" src="{% static "jquery/dist/jquery.js" %}"></script>
<script type="text/javascript" src="{% static "bootstrap/dist/js/bootstrap.js" %}"></script>
<link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.css" %}" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="{% static 'forums/schedule.css'%}" />
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Joint Cyber Command{% endblock %}</title>
</head>
<body>
 	<div id="page">
		<div id="header">
			<div id="section">
                <div>
                {% if user.is_authenticated %}
                    <p><a href={% url 'profile' %}>{{user|capfirst}}</p>
                    <p><a href={% url 'auth:logout' %}>Log Out</p>
                {% else %}
                    <p><a href={% url 'auth:login' %}>login</p>
                    <p><a href={% url 'user:signup' %}>register</p>
                {% endif %}
                </div>
                <div><a href={% url 'index' %}><img src={% static 'images/logo2.gif' %} alt="Logo" /></a></div>
			</div>
			<ul>
                <li {% block li1 %}{% endblock %}><a href={% url 'index' %}>Home</a></li>
                <li {% block li2 %}{% endblock %}><a href={% url 'forums:overview' %}>Forum</a></li>
				<li {% block li3 %}{% endblock %}><a href={% url "schedule:month_calendar" 'base' %}>Calendar</a></li>
                {% comment %}
                {% endcomment %}
				<li {% block li4 %}{% endblock %}><a href={% url 'blog:overview' %}>Blog</a></li>
				<li {% block li5 %}{% endblock %}><a href={% url 'connect' %}>Connect</a></li>
				<li {% block li6 %}{% endblock %}><a href={% url 'contact' %}>Contact us</a></li>
			</ul>
            {% block tagline %} {% endblock %}

   		</div>
		<div id="content">
            {% block submenu %}
            {% endblock %}
            {% block breadcrumb %}
            {% endblock %}
            {% block body %}
            {% endblock %}
            {% block content %}
            {% endblock %}
        </div>
		<div id="footer">
            <div>
                <div class='section'>
                    <ul>
                        <li><a href={% url 'index' %}>Home</a></li>
                        <li><a href={% url 'forums:overview' %}>Forum</a></li>
                        <li><a href={% url "schedule:month_calendar" 'base' %}>Calendar</a></li>
                        <li><a href={% url 'blog:overview' %}>Blog</a></li>
                        <li><a href={% url 'connect' %}>Connect</a></li>
                        <li><a href="contactus.html">Contact us</a></li>
                    </ul>
                </div>
                <p>&copy; Copyright 2016. CDX.</p>
            </div>
		</div>
</body>
</html>

gen-web-server/templates/connect.html
{% extends 'base.html' %}

{% block li5 %}
class='Current'
{% endblock %}
{% block body %}
<div>
    <h1>
        Connect with the base!
    </h1>
    <p>
        Enter your email to stay connected with the base and all upcoming activities.
    </p>
    <form action={% url 'connect' %} method='post'>
        {{ email_form }}
    <input type='submit' value='Submit'/>
    </form>
    {% if email %}
        <p>
        Response: 
        </P>
        <p class='boxed'>
            {% for line in data %}
            {{ line }}<br>
            {% endfor %}
        </p>
    {% endif %}
    {% if user.is_authenticated %}
        <h1>
            Search for other users: 
        </h1>
    <form action={% url 'connect' %} method='post'>
        {{ search_form }}
    <input type='submit' value='Submit'/>
    </form>
    {% for User in regUsers %}
    <p>{{User.username|capfirst}} ({{User.first_name}}, {{User.last_name}}) - {{User.last_login}}</p>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

gen-web-server/templates/contact.html
{% extends 'base.html' %}

{% block li6 %}
class='Current'
{% endblock %}
{% block body %}
<div>
    <h1>
        Contact Us
    </h1>
    <p>
        Please enter your questions or conerns and an administrator will get back to you within 24 hrs.
    </p>
    <form action={% url 'contact' %} method='post'>
        <table>
        {{ form }}
        </table>
    <input type='submit' value='Submit'/>
    </form>
</div>
{% endblock %}

gen-web-server/templates/profile.html
{% extends 'base.html' %}

{% block body %}
<div>
    <p>
        {% if searched_user %}
            <h1>
                {{searched_user.username|capfirst}}'s Profile
            </h1>
            <p><b>First Name:</b> {{searched_user.first_name}}</p>
            <p><b>Last Name:</b> {{searched_user.last_name}}</p>
            <p><b>E-mail Address:</b> {{searched_user.email}}</p>
        {% else %}
            <h1>
                {{user.username|capfirst}}'s Profile
            </h1>
            <p><b>First Name:</b> {{user.first_name}}</p>
            <p><b>Last Name:</b> {{user.last_name}}</p>
            <p><b>E-mail Address:</b> {{user.email}}</p>
        {% endif %}
    </p>
</div>
{% endblock %}

gen-web-server/templates/thankyou.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h2>
    Thank you {{name}}, <br>
    <br>
    An administrator will get back to you at {{email}} within 24 hours.<br>
    <br>
    Sincerely,<br>
    JBC Support Team<br>
    </h2>

</div>
{% endblock %}