gen-web-server/forums/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from forums.views import CategoryListView, ForumDetailView, TopicDetailView, TopicCreateView, PostCreateView


urlpatterns = patterns('',
    url(r'^$', CategoryListView.as_view(), name='overview'),
    url(r'^(?P<pk>\d+)/$', ForumDetailView.as_view(), name='forum'),
    url(r'^(?P<forum_id>\d+)/create/$', login_required(TopicCreateView.as_view()), name='topic_create'),
    url(r'^topic/(?P<pk>\d+)/$', TopicDetailView.as_view(), name='topic'),
    url(r'^topic/(?P<pk>\d+)/create/$', login_required(PostCreateView.as_view()), name='post_create'),
)

gen-web-server/gen-web-server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import index, connect, contact, profile


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('nano.blog.urls', namespace='blog')),
    url(r'^user/', include('nano.user.urls', namespace='user')),
    url(r'^user/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^connect/$', connect, name='connect'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^profile/$', profile, name='profile'),
]

gen-web-server/nano/blog/urls.py
from django.conf.urls import *

from nano.blog import views

urlpatterns = patterns('',
    url(r'^(?P<year>\d{4})/(?P<month>[01]\d)/(?P<day>[0123]\d)/$', views.list_entries_by_date),
    url(r'^(?P<year>\d{4})/(?P<month>[01]\d)/$', views.list_entries_by_year_and_month),
    url(r'^(?P<year>\d{4})/$',     views.list_entries_by_year),
    url(r'^latest/$',              views.list_latest_entries),
    url(r'^today/$',               views.list_entries_for_today),
    url(r'^$',                     views.list_entries, name='overview'),
)

gen-web-server/schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

from django.conf import settings
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import (
        CalendarByPeriodsView, CalendarView, EventView,
        OccurrenceView, EditOccurrenceView, DeleteEventView,
        EditEventView, CreateEventView, OccurrencePreview,
        CreateOccurrenceView, CancelOccurrenceView, FullCalendarView)

'''
'''
urlpatterns = patterns(
    '',
    # urls for Calendars
    url(r'^calendar/$',
    ListView.as_view(queryset=Calendar.objects.all(),
                        template_name='schedule/calendar_list.html'),
    name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(),
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name="calendar_home",
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(), 
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name="edit_occurrence"),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date"),

    # feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    
    # api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),
    url(r'^api/move_or_resize/$', 
        'schedule.views.api_move_or_resize_by_code',
        name='api_move_or_resize'),
    url(r'^api/select_create/$', 
        'schedule.views.api_select_create',
        name='api_select_create'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    )

gen-web-server/schedule/views.py
from future import standard_library
standard_library.install_aliases()
import json
import pytz
import datetime
import dateutil.parser
from urllib.parse import quote

from django.db.models import Q
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
        UpdateView, CreateView, DeleteView, ModelFormMixin, ProcessFormView)

from schedule.conf.settings import (GET_EVENTS_FUNC, OCCURRENCE_CANCEL_REDIRECT,
                                    EVENT_NAME_PLACEHOLDER)
from schedule.forms import EventForm, OccurrenceForm
from schedule.models import Calendar, Occurrence, Event
from schedule.periods import weekday_names
from schedule.utils import check_event_permissions, check_calendar_permissions, coerce_date_dict

name_space = 'scheduel:'

class CalendarViewPermissionMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(CalendarViewPermissionMixin, cls).as_view(**initkwargs)
        return check_calendar_permissions(view)


class EventEditPermissionMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(EventEditPermissionMixin, cls).as_view(**initkwargs)
        return check_event_permissions(view)


class TemplateKwargMixin(TemplateResponseMixin):
    def get_template_names(self):
        if 'template_name' in self.kwargs:
            return [self.kwargs['template_name']]
        else:
            return super(TemplateKwargMixin, self).get_template_names()


class CancelButtonMixin(object):
    def post(self, request, *args, **kwargs):
        next_url = kwargs.get('next', None)
        self.success_url = get_next_url(request, next_url)
        if "cancel" in request.POST:
            return HttpResponseRedirect(self.success_url)
        else:
            return super(CancelButtonMixin, self).post(request, *args, **kwargs)


class CalendarMixin(CalendarViewPermissionMixin, TemplateKwargMixin):
    model = Calendar
    slug_url_kwarg = 'calendar_slug'


class CalendarView(CalendarMixin, DetailView):
    template_name = 'schedule/calendar.html'


class FullCalendarView(CalendarMixin, DetailView):
    template_name="fullcalendar.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(FullCalendarView, self).get_context_data()
        context = {
            'calendar_slug': kwargs.get('calendar_slug'),
        }
        return context


class CalendarByPeriodsView(CalendarMixin, DetailView):
    template_name = 'schedule/calendar_by_period.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(request, **kwargs)
        return self.render_to_response(context)

    def get_context_data(self, request, **kwargs):
        context = super(CalendarByPeriodsView, self).get_context_data(**kwargs)
        calendar = self.object
        periods = kwargs.get('periods', None)
        try:
            date = coerce_date_dict(request.GET)
        except ValueError:
            raise Http404
        if date:
            try:
                date = datetime.datetime(**date)
            except ValueError:
                raise Http404
        else:
            date = timezone.now()
        event_list = GET_EVENTS_FUNC(request, calendar)

        if 'django_timezone' in self.request.session:
            local_timezone = pytz.timezone(request.session['django_timezone'])
        else:
            local_timezone = timezone.get_default_timezone()
        period_objects = {}
        for period in periods:
            if period.__name__.lower() == 'year':
                period_objects[period.__name__.lower()] = period(event_list, date, None, local_timezone)
            else:
                period_objects[period.__name__.lower()] = period(event_list, date, None, None, local_timezone)

        context.update({
            'date': date,
            'periods': period_objects,
            'calendar': calendar,
            'weekday_names': weekday_names,
            'here': quote(request.get_full_path()),
        })
        return context


class OccurrenceMixin(CalendarViewPermissionMixin, TemplateKwargMixin):
    model = Occurrence
    pk_url_kwarg = 'occurrence_id'
    form_class = OccurrenceForm


class OccurrenceEditMixin(EventEditPermissionMixin, OccurrenceMixin, CancelButtonMixin):
    def get_initial(self):
        initial_data = super(OccurrenceEditMixin, self).get_initial()
        _, self.object = get_occurrence(**self.kwargs)
        return initial_data


class OccurrenceView(OccurrenceMixin, DetailView):
    template_name = 'schedule/occurrence.html'


class OccurrencePreview(OccurrenceMixin, ModelFormMixin, ProcessFormView):
    template_name = 'schedule/occurrence.html'

    def get_context_data(self, **kwargs):
        context = super(OccurrencePreview, self).get_context_data()
        context = {
            'event': self.object.event,
            'occurrence': self.object,
        }
        return context


class EditOccurrenceView(OccurrenceEditMixin, UpdateView):
    template_name = 'schedule/edit_occurrence.html'


class CreateOccurrenceView(OccurrenceEditMixin, CreateView):
    template_name = 'schedule/edit_occurrence.html'


class CancelOccurrenceView(OccurrenceEditMixin, ModelFormMixin, ProcessFormView):
    template_name = 'schedule/cancel_occurrence.html'

    def post(self, request, *args, **kwargs):
        event, occurrence = get_occurrence(**kwargs)
        self.success_url = kwargs.get('next',
                        get_next_url(request, event.get_absolute_url()))
        if "cancel" not in request.POST:
            occurrence.cancel()
        return HttpResponseRedirect(self.success_url)


class EventMixin(CalendarViewPermissionMixin, TemplateKwargMixin):
    model = Event
    pk_url_kwarg = 'event_id'


class EventEditMixin(EventEditPermissionMixin, EventMixin, CancelButtonMixin):
    pass


class EventView(EventMixin, DetailView):
    template_name = 'schedule/event.html'


class EditEventView(EventEditMixin, UpdateView):
    form_class = EventForm
    template_name = 'schedule/create_event.html'


class CreateEventView(EventEditMixin, CreateView):
    form_class = EventForm
    template_name = 'schedule/create_event.html'

    def get_initial(self):
        date = coerce_date_dict(self.request.GET)
        initial_data = None
        if date:
            try:
                start = datetime.datetime(**date)
                initial_data = {
                    "start": start,
                    "end": start + datetime.timedelta(minutes=30)
                }
            except TypeError:
                raise Http404
            except ValueError:
                raise Http404
        return initial_data

    def form_valid(self, form):
        event = form.save(commit=False)
        event.creator = self.request.user
        event.calendar = get_object_or_404(Calendar, slug=self.kwargs['calendar_slug'])
        event.save()
        return HttpResponseRedirect(event.get_absolute_url())


class DeleteEventView(EventEditMixin, DeleteView):
    template_name = 'schedule/delete_event.html'

    def get_context_data(self, **kwargs):
        ctx = super(DeleteEventView, self).get_context_data(**kwargs)
        ctx['next'] = self.get_success_url()
        return ctx

    def get_success_url(self):
        """
        After the event is deleted there are three options for redirect, tried in
        this order:
        # Try to find a 'next' GET variable
        # If the key word argument redirect is set
        # Lastly redirect to the event detail of the recently create event
        """
        next_url = self.kwargs.get('next') or reverse(name_space+'day_calendar', args=[self.object.calendar.slug])
        next_url = get_next_url(self.request, next_url)
        return next_url


def get_occurrence(event_id, occurrence_id=None, year=None, month=None, day=None, hour=None, minute=None, second=None):
    """
    Because occurrences don't have to be persisted, there must be two ways to
    retrieve them. both need an event, but if its persisted the occurrence can
    be retrieved with an id. If it is not persisted it takes a date to
    retrieve it.  This function returns an event and occurrence regardless of
    which method is used.
    """
    if(occurrence_id):
        occurrence = get_object_or_404(Occurrence, id=occurrence_id)
        event = occurrence.event
    elif(all((year, month, day, hour, minute, second))):
        event = get_object_or_404(Event, id=event_id)
        occurrence = event.get_occurrence(
            datetime.datetime(int(year), int(month), int(day), int(hour), int(minute), int(second)))
        if occurrence is None:
            raise Http404
    else:
        raise Http404
    return event, occurrence


def check_next_url(next_url):
    """
    Checks to make sure the next url is not redirecting to another page.
    Basically it is a minimal security check.
    """
    if not next_url or '://' in next_url:
        return None
    return next_url


def get_next_url(request, default):
    next_url = default
    if OCCURRENCE_CANCEL_REDIRECT:
        next_url = OCCURRENCE_CANCEL_REDIRECT
    if 'next' in request.REQUEST and check_next_url(request.REQUEST['next']) is not None:
        next_url = request.REQUEST['next']
    return next_url


def api_occurrences(request):
    utc=pytz.UTC
    # version 2 of full calendar
    if '-' in request.GET.get('start'):
        convert = lambda d: datetime.datetime.strptime(d, '%Y-%m-%d')
    else:

gen-web-server/schedule/templates/schedule/_create_event_options.html
{% load staticfiles i18n %}
<a href="{{ create_event_url }}&amp;next={{here}}">
  <span class="glyphicon glyphicon-plus" ></span>
</a>

gen-web-server/schedule/templates/schedule/_daily_table.html
{% load scheduletags %}
<table class="table table-striped">
    {% for slot in slots %}
    <tr>
    <td class="col-md-1">
      <span class="time">{{ slot.start|time:"G:i" }}</span>
      {% if addable %}
      {% create_event_url calendar slot.start %}
      {% endif %}
    </td>
    <td class="col-md-4">
      {% for occ in slot.occurrences %}
            <button type="button"  class="btn {% if occ.cancelled %} btn-danger {%else%} btn-primary {% endif %}" data-toggle="modal" data-target="#{% hash_occurrence occ %}">
                  {% options occ %}
                  {% title occ %}
            </button>
      {% include 'schedule/_detail.html' with occurrence=occ %}
      {% endfor %}
    </td>
  </tr>
    {% endfor %}
</table>

gen-web-server/schedule/templates/schedule/_day_cell.html
{% load scheduletags %}
{% ifnotequal day.start.month month.start.month %}
  <td class="muted"></td>
{% else %}
  {% if day.has_occurrences %}
    <td class="btn-primary gradient">
  {% else %}
    <td>
  {% endif %}
  <a href="{% url "schedule:day_calendar" calendar.slug %}{% querystring_for_date day.start 3 True %}">
    <strong>{{day.start.day}}</strong>
  </a>
  {% ifnotequal size "small" %}
    {% include "schedule/_day_cell_big.html" %}
  {% endifnotequal %}
</td>
{% endifnotequal %}

gen-web-server/schedule/templates/schedule/_event_options.html
{% load staticfiles i18n %}

<span class="actions">
{% if edit_event %}
  <span class="edit">
  {% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="#" onclick="openURL('{{ edit_occurrence }}?next={{ here }}', event);">
          <span class="glyphicon glyphicon-pencil"></span>
        </a>
    {% else %}
        <a href="#" onclick="openEditDialog(this, '{{ edit_occurrence }}?next={{ here }}', '{{ edit_event }}?next={{ here }}', event);">
          <span class="glyphicon glyphicon-pencil"></span>
        </a>
    {% endif %}
  {% else %}
    <a href="#" onclick="openURL('{{ edit_event }}?next={{ here }}', event);">
        <span class="glyphicon glyphicon-remove"></span>
    </a>
  {% endif %}
  </span>
{% endif %}

{% if delete_event %}
<span class="delete">
  {% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="#" onclick="openURL('{{cancel_occurrence}}?next={{here}}', event);">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
    {% else %}
        <a href="#" onclick="openCancelDialog(this, '{{ cancel_occurrence }}?next={{here}}', '{{delete_event}}?next={{here}}', event);">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
    {% endif %}
  {% else %}
    <a href="#" onclick="openURL('{{delete_event}}?next={{here}}', event);">
      <span class="glyphicon glyphicon-remove"></span>
    </a>
  {% endif %}
</span>
{% endif %}
</span>

gen-web-server/schedule/templates/schedule/_event_title.html
<span class="title">{{occurrence.title}}</span>

gen-web-server/schedule/templates/schedule/_month_table.html
{% load scheduletags %}
<div class = "schedule">
<table class="table-condensed1 table-striped1">
{% if day_names %}
<thead>
  <th>&nbsp;</th>
  {% for day_name in day_names %}
    <th>{{ day_name }}</th>
  {% endfor %}
</thead>
{% endif %}
<tbody>
  {% for week in month.get_weeks %}
      <tr>
      <td>
          <a href="{% url "schedule:week_calendar" calendar.slug %}{% querystring_for_date week.start 3 True %}">
              {{week.start|date:"W"}}
          </a>
      </td>
      {% for day in week.get_days %}
    {% day_cell calendar day month size %}
      {% endfor %}
      </tr>
  {% endfor %}
</body>
</table>
</div>

gen-web-server/schedule/templates/schedule/_month_table_back.html
{% load scheduletags %}
<table class="table-condensed table-striped">
{% if day_names %}
<thead>
  <th>&nbsp;</th>
  {% for day_name in day_names %}
    <th>{{ day_name }}</th>
  {% endfor %}
</thead>
{% endif %}
<tbody>
  {% for week in month.get_weeks %}
      <tr>
      <td>
          <a href="{% url "schedule:week_calendar" calendar.slug %}{% querystring_for_date week.start 3 True %}">
              {{week.start|date:"W"}}
          </a>
      </td>
      {% for day in week.get_days %}
    {% day_cell calendar day month size %}
      {% endfor %}
      </tr>
  {% endfor %}
</body>
</table>

gen-web-server/schedule/templates/schedule/_prevnext.html
{% load scheduletags staticfiles %}
<div class="row row-centered">
    {% prev_url target calendar period %}
    &nbsp; <b>{{period_name}}</b> &nbsp;
    {% next_url target calendar period %}
</div>

gen-web-server/schedule/templates/schedule/calendar_compact_month.html
{% extends "base.html" %}
{% load scheduletags %}
{% block body %}
<h1>{{ calendar.name }}</h1>
{% month_table calendar periods.month "small" %}
{% endblock %}

gen-web-server/schedule/templates/schedule/calendar_month.html
{% extends "base.html" %}
{% load scheduletags i18n %}

{% block li3 %}
class="Current"
{% endblock %}

{% block body %}
<div class="content">
{% include "schedule/_dialogs.html" %}
<div class="row row-centered">
  <div class="calendarname">{{ calendar.name }}</div>
  {% prevnext "month_calendar" calendar periods.month "F Y"%}
  <div class="now row-centered">
    <a href="{% url "schedule:month_calendar" calendar.slug %}">
      {% trans "This month" %}
    </a>
  </div>
  <div class="center span7">
    {% month_table calendar periods.month "regular" %}
  </div>
</div>
{% comment %}
<div class="row row-centered">
  <a href="{% url "schedule:tri_month_calendar" calendar.slug %}{% querystring_for_date periods.month.start 2 True %}">
    {% trans "Three Month Calendar" %}
  </a>
  <a href="{% url "schedule:year_calendar" calendar.slug %}{% querystring_for_date periods.month.start 1 True %}">
    {% trans "Full Year Calendar" %}
  </a>
</div>
{% endcomment %}
</div>
{% endblock %}

gen-web-server/schedule/templates/schedule/calendar_year.html
{% extends "base.html" %}
{% load scheduletags i18n %}
{% block body %}
<div class="tablewrapper">
    <div class="calendarname">{{ calendar.name }}</div>
    {% prevnext "year_calendar" calendar periods.year "Y" %}
    <div class="content">
      {% for month in periods.year.get_months %}
        <div class="col-md-3">
          <div class="row row-centered">
            <button class="btn btn-custom active" href="{% url "schedule:month_calendar" calendar.slug %}{% querystring_for_date month.start 2 True %}">{{month.name}}</button>
          </div>
          <div>
            {% month_table calendar month "small" %}
          </div>
        </div>
      {% endfor %}
    </div>
<div class="navigation">
  <a href="{% url "schedule:month_calendar" calendar.slug %}">
    {% trans "Current Month Calendar" %}
  </a>
  <a href="{% url "schedule:year_calendar" calendar.slug %}">
    {% trans "Current Year Calendar" %}
  </a>
</div>
{% endblock %}

gen-web-server/schedule/templates/schedule/cancel_occurrence.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans "Delete" %}</h1>
{% trans "Are you sure that you really want to cancel this occurrence?" %}

<form action="" method="post">{% csrf_token %}
  <h2>{{ occurrence.title }}</h2>
  <strong>From</strong> {{ occurrence.start|date:_("DATETIME_FORMAT") }}
  <strong>to</strong> {{ occurrence.end|date:_("DATETIME_FORMAT") }} <br/>
  <input type="submit" value="Confirm" />
  <input type="submit" name="cancel" value="Cancel" />
</form>
{% endblock %}

gen-web-server/schedule/templates/schedule/create_event.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div>
<b>{% trans "Create or change event. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br/>
  <input type="submit" value="{% trans "Save" %}">
  <input type="submit" name="cancel" value="Cancel" />
</form>
</div>
{% endblock %}

gen-web-server/schedule/templates/schedule/edit_occurrence.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change occurrence. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br/>
  <input type="submit" value="{% trans "Save" %}">
  <input type="submit" name="cancel" value="Cancel" />
</form>
{% endblock %}